#!/bin/sh
gui() { test -n "$DISPLAY"; }
gui || exit 0
[ x"`ps ax | grep -v grep | grep plasmashell`" != x"" ] || exit 0

mkdir -p ~/.local/share/color-schemes
cp -a kde/5/share/color-schemes/Red.colors ~/.local/share/color-schemes/
