#!/bin/bash

# Install packages

export ARCH="`uname -i`"
gui() { test -n "$DISPLAY"; }

expand_names() {
 awk '
  BEGIN {
   prefix=""
   glue=""
   indent=""
  }
  /^[^ #]/ {
   prefix=""
   glue=""
   indent=""
  }
  /^[^ $#][^,]+$/ {
   prefix=$0
   print $0
  }
  /^[^ $#][^,]+,/ {
   prefix=$0
   sub(/,.*$/, "", prefix)
   glue=$0
   sub(/^[^,]+,/, "", glue)
   if (glue != "") {
    print prefix
   }
  }
  /^ / {
   this_indent=$0
   sub(/[^ ].*$/, "", this_indent)
   if (indent == "") {
    indent = this_indent
   }
   if (indent == this_indent) {
    suffix=$0
    sub(/^\s+/, "", suffix)
    print prefix glue suffix
   } else {
    print $0
   }
  }
  /^\$/ {
   print ""
   print $0
  }
  /^#/ {}
 '
}

collapse_commands() {
 awk '
  BEGIN { line="" }
  /./   { line=line " " $0; }
        { sub(/^ /, "", line) }
  /^$/  { if (line != "") { print line }; line="" }
  END   { print line }
 ' | sed -e 's/\$ *//g'
}

convert_package_list() {
 (expand_names | expand_names | expand_names | collapse_commands) < "$1"
}

if [ x"$1" = x"-n" ] || [ x"$1" = x"--dry-run" ]; then
 dry=1
 shift
else
 dry=0
fi

install_commands() {
 for i in $@; do
  if gui || (printf '%s' "$i" | grep -q -v -e '\.gui$'); then
   if [ -x "$i" ]; then
    echo ". $i"
   else
    convert_package_list "$i"
   fi
  fi
 done
}

if [ $dry -eq 0 ]; then
 OLDIFS=$IFS
 IFS=""
 if [ $# -ne 0 ]; then
  sh -c "$(install_commands "$@")"
 else
  cd "$(dirname "$0")"/..
  sh -c "$(install_commands packages/*)"
 fi
 IFS=$OLD_IFS
else
 if [ $# -ne 0 ]; then
  install_commands "$@"
 else
  cd "$(dirname "$0")"/..
  install_commands packages/*
 fi
fi
