#!/bin/bash

# Install packages

ARCH="`uname -i`"

# Install these first so they can be used while the other packages are installing
FIRST="byobu vim-enhanced wget zsh"
FIRST_GUI="firefox thunderbird dconf-editor gnome-tweak-tool synergy vim-X11"
sudo yum install $FIRST $([ -n "$DISPLAY" ] && echo -n "$FIRST_GUI")
if [ -n "$DISPLAY" ]; then
 [ "$HOSTNAME" = "tracce" ]         && synergys
 [ "$HOSTNAME" = "lady-labyrinth" ] && synergyc tracce
fi

# RPMFusion repository
sudo yum localinstall --nogpgcheck \
 http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-stable.noarch.rpm \
 http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-stable.noarch.rpm

## spot's Chromium repository
#sudo wget -NP /etc/yum.repos.d \
# http://repos.fedorapeople.org/repos/spot/chromium-stable/fedora-chromium-stable.repo

# Google Chrome repository
echo -e '[google-chrome]\nname=google-chrome\nbaseurl=http://dl.google.com/linux/chrome/rpm/stable/x86_64\nenabled=1\ngpgcheck=1' | sudo tee /etc/yum.repos.d/google-chrome.repo > /dev/null

# Adobe repository
sudo yum localinstall --nogpgcheck \
 http://linuxdownload.adobe.com/adobe-release/adobe-release-"$ARCH"-1.0-1.noarch.rpm

# Dropbox repository
[ ! -e "/etc/yum.repos.d/dropbox.repo" ] && echo -e "[Dropbox]\nname=Dropbox Repository\nbaseurl=http://linux.dropbox.com/fedora/\$releasever/\ngpgkey=http://linux.dropbox.com/fedora/rpm-public-key.asc" | sudo tee /etc/yum.repos.d/dropbox.repo > /dev/null

# Install other packages
sudo yum install redhat-lsb kernel-doc \
 cowsay dig git id3v2 ncdu nmap openssh-server p7zip{,-plugins} sl tmux w3m whois \
 pandoc{,-pdf} pdftk \
 python-{bottle,django,flup,gevent,imaging,mutagen,pip,setuptools,unidecode,which} PyYAML \
 nodejs npm \
 ruby{,-devel} \
 php-{fpm,cli,manual-en,gd,imap,magickwand,mbstring,tidy} \
 java-1.7.0-openjdk{,-devel,-javadoc} \
 lighttpd{,-fastcgi} httpd-tools

#sudo easy_install -U pip    # not sure why this is needed...
sudo pip install awscli pylast python-gnupg
sudo npm install -g coffee-script stylus tiddlywiki
sudo gem install jekyll

sudo yum groupinstall "Development Tools"

# Install packages specific to desktop installations
if [ -n "$DISPLAY" ]; then
 sudo yum install \
  xclip xsel zenity \
  gnome-shell-extension-{alternative-status-menu,gpaste,systemMonitor,user-theme} \
  gtk-{murrine,unico}-engine qt-config \
  pavucontrol paprefs pulseaudio-equalizer paman \
  gimp gimp-{data-extras,help,help-browser,fourier-plugin,lqr-plugin,resynthesizer} \
  gcolor2 easytag exfalso gpaste gthumb inkscape libreoffice ufraw{,-gimp} \
  ffmpeg lame vlc{,-extras} mplayer{,-doc} mencoder gstreamer-{ffmpeg,plugins-ugly} \
  google-chrome-stable nautilus-dropbox VirtualBox vlmc \
  nspluginwrapper alsa-plugins-pulseaudio flash-plugin icedtea-web{,-javadoc} \
  webkitgtk{,3} pywebkitgtk qtwebkit tkinter \
  SDL{,_sound}{,-devel} \
  supertux

 sudo pip install PyZenity
fi
